services:
  mcpdatadog:
    build: ./servers/mcp-datadog
    container_name: mcpdatadog
    restart: always
    env_file: ./servers/mcp-datadog/.env
    volumes:
      - ./servers/mcp-datadog:/app
    ports:
      - "8101:8000"

  hostclient:
    build: ./clients/ui-streamlit
    container_name: hostclient
    env_file: ./clients/ui-streamlit/.env
    restart: always
    volumes:
      - ./clients/ui-streamlit:/app
    ports:
      - "8501:8501"
    network_mode: "host"
    command: >
      streamlit run app.py
    depends_on:
      - mcpdatadog
